- name: Configure https webserver with nginx
  hosts: web
  vars:
    key_file: /etc/nginx/nginx.key
    cert_file: /etc/nginx/nginx.cert
    conf_file: /etc/nginx/conf.d/default.conf
    server_name: localhost
  tasks:
    - name: Enabled nginx repo
      copy: src=conf/nginx.repo dest=/etc/yum.repos.d/ 
    - name: Install Nginx Package    
      yum: name=nginx state=latest update_cache=yes
   
    - name: Copy TLS key
      copy: src=certs/nginx.key dest={{ key_file }}
      notify: restart nginx 
    - name: Copy TLS cert
      copy: src=certs/nginx.cert dest={{ cert_file }}
      notify: restart nginx 
    - name: Copy nginx config file
      template: src=conf/nginx.conf.j2 dest={{ conf_file }}
      notify: restart nginx 

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
